[package]
org = "ballerinax"
name = "financial.iso20022ToSwiftmt"
version = "0.9.2"
distribution = "2201.10.1"
authors=["Ballerina"]
keywords=["Financial", "SWIFT MT", "ISO 20022", "Conversion"]
repository="https://github.com/ballerina-platform/module-ballerinax-financial.iso20022-to-swiftmt"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "financial.iso20022"
version = "1.1.0"

[[dependency]]
org = "ballerinax"
name = "financial.swift.mt"
version = "1.0.2"
